Use docker image for managing deps

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,47 +10,36 @@ services:
 notifications:
   email: false
 
+before_cache:
+  # Save tagged docker images
+  - >
+    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
+    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
+
+cache:
+  directories:
+    - $HOME/docker
+
 matrix:
   include:
     - os: osx
       osx_image: xcode9
       compiler: clang
-      env:
-        - OPENSLL_ROOT_DIR=/usr/local/opt/openssl
-        - TESTS=OFF
-        - USE_BUNDLED_BOOST=OFF
     - os: linux
       compiler: gcc
       env:
         - CXX_VERSION=g++-8
         - CC_VERSION=gcc-8
-        - TESTS=ON
         - COVERAGE=ON
-        - USE_BUNDLED_BOOST=ON
-        - LIBSODIUM_VERSION=1.0.16
-      addons:
-        apt:
-          sources:
-            - "ubuntu-toolchain-r-test"
-          packages:
-            - "g++-8"
-            - "lcov"
     - os: linux
       compiler: clang
       env:
         - CXX_VERSION=clang++-6.0
         - CC_VERSION=clang-6.0
-        - TESTS=ON
-        - USE_BUNDLED_BOOST=ON
-        - LIBSODIUM_VERSION=1.0.16
-      addons:
-        apt:
-          sources:
-            - "ubuntu-toolchain-r-test"
-            - "llvm-toolchain-trusty-6.0"
-          packages:
-            - "clang++-6.0"
-            - "clang-6.0"
+
+before_install:
+  # Load cached docker images
+  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
 
 install:
   - ./.ci/install.sh
@@ -59,10 +48,33 @@ script:
   - $CXX --version
   - cmake --version
 
-  - ./.ci/script.sh
+  # Start the synapse server to run the tests.
+  - if [ $TRAVIS_OS_NAME == linux ]; then make synapse; fi
+
+  # Build the lib and run the test suite against synapse.
+  - |
+    if [ $TRAVIS_OS_NAME == linux ]; then
+      docker run -v `pwd`:/build --net=host \
+        -e CXX_VERSION=${CXX_VERSION} \
+        -e CC_VERSION=${CC_VERSION} \
+        -e COVERAGE=${COVERAGE} \
+        -e TRAVIS_OS_NAME=${TRAVIS_OS_NAME} \
+        mujx/mtxclient-dev:0.1.0 \
+        /bin/bash -c "./.ci/script.sh"
+    fi
+
+  # Build the lib and run the linter.
+  - |
+    if [ $TRAVIS_OS_NAME == osx ]; then
+      ./.ci/script.sh
+    fi
 
 after_success:
   # Generate coverage report and upload report to CodeCov.
-  - if [ $COVERAGE == ON ]; then make -C build/tests matrix_client_coverage; fi
-  - if [ $COVERAGE == ON ]; then ./.ci/coverage.sh; fi
-  - if [ $COVERAGE == ON ]; then bash <(curl -s https://codecov.io/bash) -f "!*tests*" || echo "Codecov failed"; fi
+  - |
+    if [ $COVERAGE == ON ]; then
+      docker run -v `pwd`:/build \
+        --net=host mujx/mtxclient-dev:0.1.0 \
+        /bin/bash -c "./.ci/coverage.sh" && \
+      bash <(curl -s https://codecov.io/bash) -f "!*tests*" || echo "Codecov failed"
+    fi
